name: dnotas
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  auto_size_text: 3.0.0
  cached_network_image: 3.3.1
  cloud_firestore: ^5.1.0
  cloud_firestore_platform_interface: ^6.2.9
  cloud_firestore_web: ^4.0.3
  collection: 1.18.0
  equatable: 2.0.5
  firebase_auth: ^5.1.2
  firebase_auth_platform_interface: ^7.4.2
  firebase_auth_web: ^5.12.4
  firebase_core: ^3.2.0
  firebase_core_platform_interface: ^5.1.0
  firebase_core_web: ^2.17.3
  firebase_performance: ^0.10.0+3
  firebase_performance_platform_interface: ^0.1.4+39
  firebase_performance_web: ^0.1.6+11
  flutter_animate: 4.5.0
  flutter_cache_manager: ^3.3.2
  font_awesome_flutter: ^10.7.0
  from_css_color: 2.0.0
  go_router: ^14.2.1
  google_fonts: ^6.2.1
  google_sign_in: ^6.2.1
  google_sign_in_android: ^6.1.27
  google_sign_in_ios: ^5.7.6
  google_sign_in_platform_interface: ^2.4.5
  google_sign_in_web: ^0.12.4+1
  http: 1.2.1
  intl: 0.19.0
  json_path: 0.7.2
  mime_type: 1.0.0
  page_transition: 2.1.0
  path_provider: 2.1.3
  path_provider_android: ^2.2.7
  path_provider_foundation: 2.4.0
  path_provider_platform_interface: 2.1.2
  plugin_platform_interface: 2.1.8
  provider: 6.1.2
  rxdart: 0.27.7
  shared_preferences: ^2.2.3
  shared_preferences_android: ^2.2.3
  shared_preferences_foundation: ^2.4.0
  shared_preferences_platform_interface: ^2.3.2
  shared_preferences_web: ^2.3.0
  sign_in_with_apple: ^6.1.1
  sign_in_with_apple_platform_interface: ^1.1.0
  sign_in_with_apple_web: ^2.1.0
  sqflite: ^2.3.3+1
  stream_transform: 2.1.0
  timeago: ^3.7.0
  url_launcher: ^6.3.0
  url_launcher_android: ^6.3.4
  url_launcher_ios: ^6.3.1
  url_launcher_platform_interface: 2.3.2

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

  crypto: any
  http_parser: any

dependency_overrides:
  http: 1.2.1
  uuid: ^4.0.0

dev_dependencies:
  flutter_launcher_icons: 0.13.1
  flutter_lints: 4.0.0
  image: ^4.2.0
  lints: 4.0.0

  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: 'launcher_icon'
  ios: true
  web:
    generate: true
  image_path: 'assets/images/app_launcher_icon.jpeg'
  adaptive_icon_background: '#00000000'
  adaptive_icon_foreground: 'assets/images/adaptive_foreground_icon.png'

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/
    - assets/videos/
    - assets/audios/
    - assets/lottie_animations/
    - assets/rive_animations/
    - assets/pdfs/
